export const ADD_PARAMS = 'ADD_PARAMS';
export const DELETE_PARAM = 'DELETE_PARAM';
export const SAVE_BATTLES = 'SAVE_BATTLES';
export const SEARCH_API_INTIATE = 'SEARCH_API_INTIATE';
export const SAVE_LOCATIONS = 'SAVE_LOCATIONS';
